### ISSUE TITLE
Problems with parsing archetype from CKM (blood pressure) with adl-parser-1.0.9

### ISSUE THREAD

**Issue by GeorgFette** [ethercis/ehrservice#12]
I tried to download an archetype (uid=b1506a87-9bf2-4978-9eed-6ceecb0c2be9; openEHR-EHR-OBSERVATION.blood_pressure.v1) and parse it with the 3rdparty party parser that is included in the project. However I end up with this exception:

ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Exception in thread "main" se.acode.openehr.parser.TokenMgrError: Lexical error at line 1, column 33.  Encountered: "=" (61), after : "uid"
	at se.acode.openehr.parser.ADLParserTokenManager.getNextToken(ADLParserTokenManager.java:31176)
	at se.acode.openehr.parser.ADLParser.jj_ntk(ADLParser.java:7209)
	at se.acode.openehr.parser.ADLParser.controlled(ADLParser.java:438)
	at se.acode.openehr.parser.ADLParser.archetype(ADLParser.java:222)
	at se.acode.openehr.parser.ADLParser.parse(ADLParser.java:101)
	at StarterTest.main(StarterTest.java:47)

What could have gone wrong ?

**Comment by chevalleyc** [comment]
There has been some changes in the ADL formatting and I'm not sure whether your issue is related. You might try with the latest code base at https://github.com/openEHR/java-libs . On an EtherCIS level, we don't use ADL parsing anymore; it was originally planned to build templates from archetypes, but now we only use operational templates as produced by the template designer.

**Comment by chevalleyc** [comment]
Closed due to no recent activities. Please feel free to reopen if needed. Thanks
